[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200

build_flags =
  -D TINY_GSM_MODEM_SIM7600
  -DUNIT_TEST
  ${sysenv.FIRMWARE_VERSION_BUILD_FLAG}
  ${sysenv.OTA_BUILD_FLAGS}
check_tool = cppcheck
check_flags =
  cppcheck: --enable=all --inconclusive

test_filter = *

lib_deps =
  https://github.com/vshymanskyy/TinyGSM.git
  bblanchon/ArduinoJson @ ^7.0.0
  https://github.com/mobizt/Firebase-ESP-Client.git
  https://github.com/Xinyuan-LilyGO/LilyGo-Modem-Series.git
  mikalhart/TinyGPSPlus@^1.0.3
